pmem: Fix 'phys_mem_access_prot' build error
Redmine: fixes #15460

Fix the following build error:

  CC      drivers/misc/pmem.o
drivers/misc/pmem.c:441: error: conflicting types for 'phys_mem_access_prot'
/home/skuribay/git/linux/arch/arm/include/asm/pgtable.h:342: error: previous declaration of 'phys_mem_access_prot' was here
make[2]: *** [drivers/misc/pmem.o] Error 1
make[1]: *** [drivers/misc] Error 2
make: *** [drivers] Error 2

commit d907387c42e9e39261629890e45a08ef4c3ed3fe (ARM: 6383/1: Implement
phys_mem_access_prot() to avoid attributes aliasing) introduced the same
symbol name with a pmem-local API.

Now 'phys_mem_access_prot' is reserved for system-wide API, so fix the
pmem-local one, with 'pmem_' prefix.

Reported-by: Teppei Kamijou <teppei.kamijou.yb@renesas.com>
Signed-off-by: Shinya Kuribayashi <shinya.kuribayashi.px@renesas.com>